name: Tests

on:
    push:
      branches: [ main ]

jobs:
    deploy:
       runs-on: ubuntu-latest
       steps:
        - uses: actions/checkout@master
        - name: "Initialize Python 3.9"
          uses: actions/setup-python@v1
          with:
            python-version: 3.9

        - name: "docker-compose up"
          run: |
            docker-compose up -d

        - name: "Run tests"
          run: |
            docker exec yandex_music_service_auth-k_1 python tests.py
